/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.jowlasnyprojekt;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JFileChooser;

/**
 *
 * @author dell
 */
public class joWlasnyProjekt extends javax.swing.JFrame {

    /**
     * Creates new form joWlasnyProjekt
     */
    public joWlasnyProjekt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jo_buttonGroupGender = new javax.swing.ButtonGroup();
        jo_jPanelMain = new javax.swing.JPanel();
        jo_jLabelFirstName = new javax.swing.JLabel();
        jo_jTextFieldFirstName = new javax.swing.JTextField();
        jo_jLabelLastName = new javax.swing.JLabel();
        jo_jTextFieldLastName = new javax.swing.JTextField();
        jo_jLabelGender = new javax.swing.JLabel();
        jo_jRadioButtonMale = new javax.swing.JRadioButton();
        jo_jRadioButtonFemale = new javax.swing.JRadioButton();
        jo_jTextFieldLogin = new javax.swing.JTextField();
        jo_jLabelLogin = new javax.swing.JLabel();
        jo_jLabelPassword = new javax.swing.JLabel();
        jo_jPasswordFieldPassword = new javax.swing.JPasswordField();
        jo_jCheckBoxShowPassword = new javax.swing.JCheckBox();
        jo_jLabelImage = new javax.swing.JLabel();
        jo_jButtonClear = new javax.swing.JButton();
        jo_jMenuBar = new javax.swing.JMenuBar();
        jo_jMenuFile = new javax.swing.JMenu();
        jo_jMenuItemSave = new javax.swing.JMenuItem();
        jo_jMenuItemLoad = new javax.swing.JMenuItem();
        jo_jMenuItemClose = new javax.swing.JMenuItem();
        jo_jMenuEdit = new javax.swing.JMenu();
        jo_jMenuChangeFont = new javax.swing.JMenu();
        jo_jMenuChangeBackground = new javax.swing.JMenu();
        jo_jMenuItemRed = new javax.swing.JMenuItem();
        jo_jMenuItemBlue = new javax.swing.JMenuItem();
        jo_jMenuItemGreen = new javax.swing.JMenuItem();
        jo_jMenuAbout = new javax.swing.JMenu();
        jo_jMenuItemAbout = new javax.swing.JMenuItem();
        jo_jMenuItemHelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Logowanie");

        jo_jLabelFirstName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jo_jLabelFirstName.setText("Imię: ");

        jo_jTextFieldFirstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jo_jTextFieldFirstName.setForeground(new java.awt.Color(153, 153, 153));

        jo_jLabelLastName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jo_jLabelLastName.setText("Nazwisko: ");

        jo_jTextFieldLastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jo_jTextFieldLastName.setForeground(new java.awt.Color(153, 153, 153));

        jo_jLabelGender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jo_jLabelGender.setText("Płeć: ");

        jo_buttonGroupGender.add(jo_jRadioButtonMale);
        jo_jRadioButtonMale.setText("Mężczyzna");

        jo_buttonGroupGender.add(jo_jRadioButtonFemale);
        jo_jRadioButtonFemale.setText("Kobieta");

        jo_jTextFieldLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jo_jTextFieldLogin.setForeground(new java.awt.Color(153, 153, 153));
        jo_jTextFieldLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jo_jLabelLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jo_jLabelLogin.setText("Login: ");

        jo_jLabelPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jo_jLabelPassword.setText("Hasło: ");

        jo_jPasswordFieldPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jo_jPasswordFieldPassword.setForeground(new java.awt.Color(153, 153, 153));
        jo_jPasswordFieldPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jo_jCheckBoxShowPassword.setText("Pokaż Hasło");
        jo_jCheckBoxShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jo_jCheckBoxShowPasswordActionPerformed(evt);
            }
        });

        jo_jLabelImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Documents\\programowanie\\ZADANIA GITHUB\\netbeans\\11_wlasny_projekt_aplikacji\\logo.png")); // NOI18N

        jo_jButtonClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jo_jButtonClear.setText("Wyczyść");
        jo_jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jo_jButtonClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jo_jPanelMainLayout = new javax.swing.GroupLayout(jo_jPanelMain);
        jo_jPanelMain.setLayout(jo_jPanelMainLayout);
        jo_jPanelMainLayout.setHorizontalGroup(
            jo_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jo_jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jo_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jo_jPanelMainLayout.createSequentialGroup()
                        .addGroup(jo_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jo_jPanelMainLayout.createSequentialGroup()
                                .addGroup(jo_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jo_jLabelLastName)
                                    .addComponent(jo_jLabelFirstName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jo_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jo_jTextFieldFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                    .addComponent(jo_jTextFieldLastName)))
                            .addGroup(jo_jPanelMainLayout.createSequentialGroup()
                                .addComponent(jo_jLabelGender)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jo_jRadioButtonMale)
                                .addGap(18, 18, 18)
                                .addComponent(jo_jRadioButtonFemale))
                            .addGroup(jo_jPanelMainLayout.createSequentialGroup()
                                .addGroup(jo_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jo_jLabelLogin)
                                    .addComponent(jo_jLabelPassword))
                                .addGap(34, 34, 34)
                                .addGroup(jo_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jo_jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jo_jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jo_jCheckBoxShowPassword))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                        .addComponent(jo_jLabelImage))
                    .addGroup(jo_jPanelMainLayout.createSequentialGroup()
                        .addComponent(jo_jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jo_jPanelMainLayout.setVerticalGroup(
            jo_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jo_jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jo_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jo_jPanelMainLayout.createSequentialGroup()
                        .addComponent(jo_jLabelImage)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jo_jPanelMainLayout.createSequentialGroup()
                        .addGroup(jo_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jo_jLabelFirstName)
                            .addComponent(jo_jTextFieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jo_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jo_jLabelLastName)
                            .addComponent(jo_jTextFieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jo_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jo_jLabelGender)
                            .addComponent(jo_jRadioButtonMale)
                            .addComponent(jo_jRadioButtonFemale))
                        .addGap(36, 36, 36)
                        .addGroup(jo_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jo_jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jo_jLabelLogin))
                        .addGap(18, 18, 18)
                        .addGroup(jo_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jo_jLabelPassword)
                            .addComponent(jo_jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jo_jCheckBoxShowPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(jo_jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jo_jMenuFile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jo_jMenuFile.setText("Plik");
        jo_jMenuFile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jo_jMenuItemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jo_jMenuItemSave.setText("Zapisz");
        jo_jMenuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jo_jMenuItemSaveActionPerformed(evt);
            }
        });
        jo_jMenuFile.add(jo_jMenuItemSave);

        jo_jMenuItemLoad.setText("Wczytaj");
        jo_jMenuItemLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jo_jMenuItemLoadActionPerformed(evt);
            }
        });
        jo_jMenuFile.add(jo_jMenuItemLoad);

        jo_jMenuItemClose.setText("Zamknij");
        jo_jMenuItemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jo_jMenuItemCloseActionPerformed(evt);
            }
        });
        jo_jMenuFile.add(jo_jMenuItemClose);

        jo_jMenuBar.add(jo_jMenuFile);

        jo_jMenuEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jo_jMenuEdit.setText("Edycja");
        jo_jMenuEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jo_jMenuChangeFont.setText("Zmień czcionkę");
        jo_jMenuEdit.add(jo_jMenuChangeFont);

        jo_jMenuChangeBackground.setText("Zmień tło");

        jo_jMenuItemRed.setText("Czerwony");
        jo_jMenuItemRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jo_jMenuItemRedActionPerformed(evt);
            }
        });
        jo_jMenuChangeBackground.add(jo_jMenuItemRed);

        jo_jMenuItemBlue.setText("Niebieski");
        jo_jMenuItemBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jo_jMenuItemBlueActionPerformed(evt);
            }
        });
        jo_jMenuChangeBackground.add(jo_jMenuItemBlue);

        jo_jMenuItemGreen.setText("Zielony");
        jo_jMenuItemGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jo_jMenuItemGreenActionPerformed(evt);
            }
        });
        jo_jMenuChangeBackground.add(jo_jMenuItemGreen);

        jo_jMenuEdit.add(jo_jMenuChangeBackground);

        jo_jMenuBar.add(jo_jMenuEdit);

        jo_jMenuAbout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jo_jMenuAbout.setText("O Programie");
        jo_jMenuAbout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jo_jMenuItemAbout.setText("O Programie");
        jo_jMenuAbout.add(jo_jMenuItemAbout);

        jo_jMenuItemHelp.setText("Help");
        jo_jMenuItemHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jo_jMenuItemHelpActionPerformed(evt);
            }
        });
        jo_jMenuAbout.add(jo_jMenuItemHelp);

        jo_jMenuBar.add(jo_jMenuAbout);

        setJMenuBar(jo_jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jo_jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jo_jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jo_jCheckBoxShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jo_jCheckBoxShowPasswordActionPerformed
        if(jo_jCheckBoxShowPassword.isSelected()){
            jo_jPasswordFieldPassword.setEchoChar((char)0);
        }else{
            jo_jPasswordFieldPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_jo_jCheckBoxShowPasswordActionPerformed

    private void jo_jMenuItemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jo_jMenuItemCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jo_jMenuItemCloseActionPerformed

    private void jo_jMenuItemHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jo_jMenuItemHelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jo_jMenuItemHelpActionPerformed

    private void jo_jMenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jo_jMenuItemSaveActionPerformed
        saveSettings();
    }//GEN-LAST:event_jo_jMenuItemSaveActionPerformed

    private void jo_jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jo_jButtonClearActionPerformed
        clearSettings();
    }//GEN-LAST:event_jo_jButtonClearActionPerformed

    private void jo_jMenuItemLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jo_jMenuItemLoadActionPerformed
        loadSettings();
    }//GEN-LAST:event_jo_jMenuItemLoadActionPerformed

    private void jo_jMenuItemRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jo_jMenuItemRedActionPerformed
        jo_jPanelMain.setBackground(Color.RED);
    }//GEN-LAST:event_jo_jMenuItemRedActionPerformed

    private void jo_jMenuItemBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jo_jMenuItemBlueActionPerformed
        jo_jPanelMain.setBackground(Color.BLUE);
    }//GEN-LAST:event_jo_jMenuItemBlueActionPerformed

    private void jo_jMenuItemGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jo_jMenuItemGreenActionPerformed
        jo_jPanelMain.setBackground(Color.GREEN);
    }//GEN-LAST:event_jo_jMenuItemGreenActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void saveSettings(){
        try{
            FileWriter fw = new FileWriter(fileAccount);
            fw.write("Imię: ");
            fw.write(jo_jTextFieldFirstName.getText());
            fw.write("\n");
            fw.write("Nazwisko: ");
            fw.write(jo_jTextFieldLastName.getText());
            fw.write("\n");
            String gender = "N";
            if(jo_jRadioButtonFemale.isSelected()){
                gender = "Kobieta";
            }else if(jo_jRadioButtonMale.isSelected()){
                gender = "Mężczyzna";
            }
            fw.write("Płeć: "+gender);
            fw.write("\n");
            fw.write("Login: ");
            fw.write(jo_jTextFieldLogin.getText());
            fw.write("\n");
            fw.write("Hasło: ");
            fw.write(jo_jPasswordFieldPassword.getText());
            fw.close();
        }catch(IOException ex){
            System.out.println(ex.toString());
        }
    }
    
    private void loadSettings(){
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.showDialog(this, "Wybierz plik tekstowy");
        
    }
    
    private void clearSettings(){
        jo_jTextFieldFirstName.setText("");
        jo_jTextFieldLastName.setText("");
        jo_jTextFieldLogin.setText("");
        jo_jPasswordFieldPassword.setText("");
        jo_buttonGroupGender.clearSelection();
    }
    
    File fileAccount = new File("account.txt");
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(joWlasnyProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(joWlasnyProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(joWlasnyProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(joWlasnyProjekt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new joWlasnyProjekt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup jo_buttonGroupGender;
    private javax.swing.JButton jo_jButtonClear;
    private javax.swing.JCheckBox jo_jCheckBoxShowPassword;
    private javax.swing.JLabel jo_jLabelFirstName;
    private javax.swing.JLabel jo_jLabelGender;
    private javax.swing.JLabel jo_jLabelImage;
    private javax.swing.JLabel jo_jLabelLastName;
    private javax.swing.JLabel jo_jLabelLogin;
    private javax.swing.JLabel jo_jLabelPassword;
    private javax.swing.JMenu jo_jMenuAbout;
    private javax.swing.JMenuBar jo_jMenuBar;
    private javax.swing.JMenu jo_jMenuChangeBackground;
    private javax.swing.JMenu jo_jMenuChangeFont;
    private javax.swing.JMenu jo_jMenuEdit;
    private javax.swing.JMenu jo_jMenuFile;
    private javax.swing.JMenuItem jo_jMenuItemAbout;
    private javax.swing.JMenuItem jo_jMenuItemBlue;
    private javax.swing.JMenuItem jo_jMenuItemClose;
    private javax.swing.JMenuItem jo_jMenuItemGreen;
    private javax.swing.JMenuItem jo_jMenuItemHelp;
    private javax.swing.JMenuItem jo_jMenuItemLoad;
    private javax.swing.JMenuItem jo_jMenuItemRed;
    private javax.swing.JMenuItem jo_jMenuItemSave;
    private javax.swing.JPanel jo_jPanelMain;
    private javax.swing.JPasswordField jo_jPasswordFieldPassword;
    private javax.swing.JRadioButton jo_jRadioButtonFemale;
    private javax.swing.JRadioButton jo_jRadioButtonMale;
    private javax.swing.JTextField jo_jTextFieldFirstName;
    private javax.swing.JTextField jo_jTextFieldLastName;
    private javax.swing.JTextField jo_jTextFieldLogin;
    // End of variables declaration//GEN-END:variables
}
